make0:
	make -C "./Experiments/12_AUGUST_2022_1h29/GA/reproductionProp/0/"
make1:
	make -C "./Experiments/12_AUGUST_2022_1h29/GA/reproductionProp/0.25/"
make2:
	make -C "./Experiments/12_AUGUST_2022_1h29/GA/reproductionProp/0.5/"
make3:
	make -C "./Experiments/12_AUGUST_2022_1h29/GA/reproductionProp/0.75/"
make4:
	make -C "./Experiments/12_AUGUST_2022_1h29/GA/reproductionProp/1/"
make5:
	make -C "./Experiments/12_AUGUST_2022_1h29/GA/tournamentSize/0/"
make6:
	make -C "./Experiments/12_AUGUST_2022_1h29/GA/tournamentSize/0.25/"
make7:
	make -C "./Experiments/12_AUGUST_2022_1h29/GA/tournamentSize/0.5/"
make8:
	make -C "./Experiments/12_AUGUST_2022_1h29/GA/tournamentSize/0.75/"
make9:
	make -C "./Experiments/12_AUGUST_2022_1h29/GA/tournamentSize/1/"
make10:
	make -C "./Experiments/12_AUGUST_2022_1h29/GA/crossoverProp/0/"
make11:
	make -C "./Experiments/12_AUGUST_2022_1h29/GA/crossoverProp/0.25/"
make12:
	make -C "./Experiments/12_AUGUST_2022_1h29/GA/crossoverProp/0.5/"
make13:
	make -C "./Experiments/12_AUGUST_2022_1h29/GA/crossoverProp/0.75/"
make14:
	make -C "./Experiments/12_AUGUST_2022_1h29/GA/crossoverProp/1/"
make15:
	make -C "./Experiments/12_AUGUST_2022_1h29/GA/mutationType/SingleBitInversion/"
make16:
	make -C "./Experiments/12_AUGUST_2022_1h29/GA/mutationType/BitWisInversion/"
make17:
	make -C "./Experiments/12_AUGUST_2022_1h29/GA/mutationType/RandomSelection/"
make18:
	make -C "./Experiments/12_AUGUST_2022_1h29/GA/selectionSize/0/"
make19:
	make -C "./Experiments/12_AUGUST_2022_1h29/GA/selectionSize/5/"
make20:
	make -C "./Experiments/12_AUGUST_2022_1h29/GA/selectionSize/10/"
make21:
	make -C "./Experiments/12_AUGUST_2022_1h29/GA/selectionSize/25/"
make22:
	make -C "./Experiments/12_AUGUST_2022_1h29/GA/selectionSize/50/"
make23:
	make -C "./Experiments/12_AUGUST_2022_1h29/GA/populationSize/300/"
make24:
	make -C "./Experiments/12_AUGUST_2022_1h29/GA/populationSize/50/"
make25:
	make -C "./Experiments/12_AUGUST_2022_1h29/GA/populationSize/100/"
make26:
	make -C "./Experiments/12_AUGUST_2022_1h29/GA/populationSize/150/"
make27:
	make -C "./Experiments/12_AUGUST_2022_1h29/GA/populationSize/200/"
make28:
	make -C "./Experiments/12_AUGUST_2022_1h29/GA/numGenerations/10/"
make29:
	make -C "./Experiments/12_AUGUST_2022_1h29/GA/numGenerations/75/"
make30:
	make -C "./Experiments/12_AUGUST_2022_1h29/GA/numGenerations/150/"
make31:
	make -C "./Experiments/12_AUGUST_2022_1h29/GA/numGenerations/225/"
make32:
	make -C "./Experiments/12_AUGUST_2022_1h29/GA/numGenerations/300/"
make33:
	make -C "./Experiments/12_AUGUST_2022_1h29/GA/nCrossOver/0/"
make34:
	make -C "./Experiments/12_AUGUST_2022_1h29/GA/nCrossOver/5/"
make35:
	make -C "./Experiments/12_AUGUST_2022_1h29/GA/nCrossOver/10/"
make36:
	make -C "./Experiments/12_AUGUST_2022_1h29/GA/nCrossOver/25/"
make37:
	make -C "./Experiments/12_AUGUST_2022_1h29/GA/nCrossOver/50/"
make38:
	make -C "./Experiments/12_AUGUST_2022_1h29/GA/crossOverType/OnePointCrossOver/"
make39:
	make -C "./Experiments/12_AUGUST_2022_1h29/GA/crossOverType/NPointCrossOver/"
make40:
	make -C "./Experiments/12_AUGUST_2022_1h29/GA/crossOverType/SegmentedCrossOver/"
make41:
	make -C "./Experiments/12_AUGUST_2022_1h29/GA/crossOverType/UniformCrossOver/"
make42:
	make -C "./Experiments/12_AUGUST_2022_1h29/GA/crossOverType/ShuffleCrossOver/"
make43:
	make -C "./Experiments/12_AUGUST_2022_1h29/GA/mutationProp/0/"
make44:
	make -C "./Experiments/12_AUGUST_2022_1h29/GA/mutationProp/0.25/"
make45:
	make -C "./Experiments/12_AUGUST_2022_1h29/GA/mutationProp/0.5/"
make46:
	make -C "./Experiments/12_AUGUST_2022_1h29/GA/mutationProp/0.75/"
make47:
	make -C "./Experiments/12_AUGUST_2022_1h29/GA/mutationProp/1/"
